# Generated by Django 3.2.4 on 2021-06-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pokemon', models.IntegerField()),
                ('name', models.CharField(max_length=15, unique=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonsEvol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evol', models.IntegerField()),
                ('id_pokemon', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=15)),
                ('detail', models.CharField(max_length=15)),
                ('info', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('base_stat', models.IntegerField()),
            ],
        ),
    ]
